export enum MusicGenre {
  Default = "All",
  KnvZfZ7vAvv = "Alternative",
  KnvZfZ7vAve = "Ballads/Romantic",
  KnvZfZ7vAvd = "Blues",
  KnvZfZ7vAvA = "Chanson Francaise",
  KnvZfZ7vAvk = "Children's Music",
  KnvZfZ7vAeJ = "Classical",
  KnvZfZ7vAv6 = "Country",
  KnvZfZ7vAvF = "Dance & Electronic",
  KnvZfZ7vAva = "Folk",
  KnvZfZ7vAv1 = "Hip/Hop & Rap",
  KnvZfZ7vAvJ = "Holiday",
  KnvZfZ7vAvE = "Jazz",
  KnvZfZ7vAJ6 = "Latin",
  KnvZfZ7vAvI = "Medieval Renaissance",
  KnvZfZ7vAvt = "Metal",
  KnvZfZ7vAvn = "New Age",
  KnvZfZ7vAvl = "Other",
  KnvZfZ7vAev = "Pop",
  KnvZfZ7vAee = "RnB",
  KnvZfZ7vAed = "Reggae",
  KnvZfZ7vAe7 = "Religious",
  KnvZfZ7vAeA = "Rock",
  KnvZfZ7vAeF = "World",
}
export enum SportsGenre {
  Default = "All",
  KnvZfZ7vAen = "Badminton",
  KnvZfZ7vAel = "Bandy",
  KnvZfZ7vAdv = "Baseball",
  KnvZfZ7vAde = "Basketball",
  KnvZfZ7vAdA = "Boxing",
  KnvZfZ7vAda = "Cycling",
  KnvZfZ7vAd1 = "Equestrian",
  KnvZfZ7vAJF = "eSports",
  KnvZfZ7vAdE = "Football",
  KnvZfZ7vAdt = "Golf",
  KnvZfZ7vAdI = "Hockey",
  KnvZfZ7vA7v = "Ice Skating",
  KnvZfZ7vA77 = "Lacrosse",
  KnvZfZ7vA7d = "Martial Arts",
  KnvZfZ7vA71 = "Rugby",
  KnvZfZ7vAd6 = "Skiing",
  KnvZfZ7vA7E = "Soccer",
  KnvZfZ7vA7n = "Swimming",
  KnvZfZ7vAAv = "Tennis",
  KnvZfZ7vAA7 = "Volleyball",
  KnvZfZ7vAAk = "Wrestling",
}

export enum ArtsGenre {
  Default = "All",
  KnvZfZ7v7na = "Children's Theatre",
  KnvZfZ7v7n1 = "Circus & Specialty Acts",
  KnvZfZ7v7nJ = "Classical",
  KnvZfZ7vAe1 = "Comedy",
  KnvZfZ7v7nI = "Dance",
  KnvZfZ7v7nn = "Fashion",
  KnvZfZ7v7nl = "Fine Arts",
  KnvZfZ7v7lv = "Magic & Illusion",
  KnvZfZ7v7lk = "Opera",
  KnvZfZ7v7lF = "Puppetry",
  KnvZfZ7v7l1 = "Theatre",
}

export enum FamilyGenre {
  Default = "All",
  KnvZfZ7v7lF = "Puppetry",
  KnvZfZ7v7lv = "Magic & Illusion",
  KnvZfZ7v7na = "Children's Theatre",
  KnvZfZ7vAeE = "Fairs/Festivals",
  KnvZfZ7vAvk = "Children's Music",
  KnvZfZ7vA1n = "Miscellaneous",
}

