export const timezones: { [key: string]: number } = {
  NST: -3,
  ADT: -3,
  AST: -4,
  EST: -5,
  CST: -6,
  MST: -7,
  PST: -8,
  AKST: -9,
  HST: -10,
  GMT: +0,
  WET: +0,
  CET: +1,
  BST: +1,
  AWST: +8,
  ACWST: +8,
  ACST: +9,
  AEST: +10,
  ACDT: +10,
  AEDT: +11,
  LHDT: +11, // Assuming Lord Howe Daylight Time has the same offset as AEDT
  NZDT: +13,
  CHADT: +13,
};
